/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "../../../..";

export interface LinksCreateRequest {
    linkType: DevRevBeta.LinkType;
    /** The ID of the source object. */
    source: string;
    /** The ID of the target object. */
    target: string;
}
