/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "../../../..";

export interface LinksListRequest {
    object: string;
    cursor?: string;
    direction?: DevRevBeta.LinksDirection;
    limit?: number;
    linkType?: DevRevBeta.LinkType | DevRevBeta.LinkType[];
    mode?: DevRevBeta.ListMode;
    types?: DevRevBeta.LinkType | DevRevBeta.LinkType[];
}
