/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors";
import * as DevRevBeta from "..";

export class InternalServerError extends errors.DevRevBetaError {
    constructor(body: DevRevBeta.ErrorInternalServerError) {
        super({
            message: "InternalServerError",
            statusCode: 500,
            body: body,
        });
        Object.setPrototypeOf(this, InternalServerError.prototype);
    }
}
