/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors";
import * as DevRevBeta from "..";

export class NotFoundError extends errors.DevRevBetaError {
    constructor(body: DevRevBeta.ErrorNotFound) {
        super({
            message: "NotFoundError",
            statusCode: 404,
            body: body,
        });
        Object.setPrototypeOf(this, NotFoundError.prototype);
    }
}
