/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors";
import * as DevRevBeta from "..";

export class TooManyRequestsError extends errors.DevRevBetaError {
    constructor(body: DevRevBeta.ErrorTooManyRequests) {
        super({
            message: "TooManyRequestsError",
            statusCode: 429,
            body: body,
        });
        Object.setPrototypeOf(this, TooManyRequestsError.prototype);
    }
}
