/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors";
import * as DevRevBeta from "..";

export class UnauthorizedError extends errors.DevRevBetaError {
    constructor(body: DevRevBeta.ErrorUnauthorized) {
        super({
            message: "UnauthorizedError",
            statusCode: 401,
            body: body,
        });
        Object.setPrototypeOf(this, UnauthorizedError.prototype);
    }
}
