/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "../../../..";

export interface SysUsersListRequest {
    cursor?: string;
    limit?: number;
    mode?: DevRevBeta.ListMode;
    sortBy?: string | string[];
}
