/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "../../../..";

export interface RevOrgsUpdateRequest {
    /**
     * Schema fragment IDs associated with this Rev organization.
     *
     */
    customSchemaFragments?: string[];
    /** Description of the Rev organization. */
    description?: string;
    /** Customer chosen name for the Rev organization. */
    displayName?: string;
    /** Company's domain name. Example - 'devrev.ai'. */
    domain?: string;
    environment?: DevRevBeta.OrgEnvironment;
    /**
     * External ref is a custom unique identifier which is a reference to
     * an unique id for this organization's data in some system of
     * records.
     *
     */
    externalRef?: string;
    /** The ID of Rev organization to update. */
    id: string;
    /** The tier of the RevOrg. */
    tier?: string;
}
