/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "../../../..";

export interface RevOrgsListRequest {
    createdBy?: string | string[];
    createdDateAfter?: string;
    createdDateBefore?: string;
    cursor?: string;
    customFieldFilter?: string | string[];
    externalRef?: string | string[];
    limit?: number;
    mode?: DevRevBeta.ListMode;
    modifiedDateAfter?: string;
    modifiedDateBefore?: string;
    sortBy?: string | string[];
}
