/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "../../../..";

export interface RevOrgsCreateRequest {
    /** Application-defined custom fields. */
    customFields?: Record<string, unknown>;
    /**
     * Schema fragment IDs associated with this Rev organization.
     *
     */
    customSchemaFragments?: string[];
    /** Description of the Rev organization. */
    description?: string;
    /** Name of the Rev organization. */
    displayName: string;
    /** Company's domain name. Example - 'devrev.ai'. */
    domain?: string;
    environment?: DevRevBeta.OrgEnvironment;
    /**
     * External ref is a custom unique identifier which is a reference to
     * an unique id for this organization's data in some system of
     * records.
     *
     */
    externalRef?: string;
    /** The tier of the RevOrg. */
    tier?: string;
}
