/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RevUsersUpdateRequest {
    /** Updated description of the Rev user. */
    description?: string;
    /** Updated display name of the Rev user. */
    displayName?: string;
    /** Updated email address of the Rev user. */
    email?: string;
    /** Updated external ref value of the Rev user. */
    externalRef?: string;
    /** The ID of Rev user to update. */
    id: string;
}
