/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "../../../..";

export interface RevUsersListRequest {
    createdBy?: string | string[];
    createdDateAfter?: string;
    createdDateBefore?: string;
    cursor?: string;
    email?: string | string[];
    externalRef?: string | string[];
    limit?: number;
    mode?: DevRevBeta.ListMode;
    modifiedDateAfter?: string;
    modifiedDateBefore?: string;
    revOrg?: string | string[];
    sortBy?: string | string[];
}
