/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UnlinkRevUserFromRevOrgRequest {
    /** The don of the rev org to unlink the rev user from. */
    revOrgDon: string;
    /** The don of the rev user to unlink. */
    userDon: string;
}
