/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export interface AtomBase {
    createdBy?: DevRevBeta.UserSummary;
    /** Timestamp when the object was created. */
    createdDate?: string;
    /** Human-readable object ID unique to the Dev organization. */
    displayId?: string;
    /** Globally unique object ID. */
    id: string;
    modifiedBy?: DevRevBeta.UserSummary;
    /** Timestamp when the object was last modified. */
    modifiedDate?: string;
}
