/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

/**
 * The response for updating a conversation.
 */
export interface ConversationsUpdateResponse {
    conversation: DevRevBeta.Conversation;
}
