/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export interface ConversationsUpdateRequestTags {
    /** Sets the tag IDs to the provided tags. */
    set?: DevRevBeta.SetTagWithValue[];
}
