/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

/**
 * The response to getting a conversation's information.
 */
export interface ConversationsGetResponse {
    conversation: DevRevBeta.Conversation;
}
