/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

/**
 * The response to creating a new conversation.
 */
export interface ConversationsCreateResponse {
    conversation: DevRevBeta.Conversation;
}
