/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export interface ConversationSummary extends DevRevBeta.AtomBaseSummary {
    /** Title of the conversation object. */
    title?: string;
}
