/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export interface ConversationsExportResponse {
    /** The resulting collection of conversation items. */
    conversations: DevRevBeta.Conversation[];
}
