/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ConversationsCreateRequestTypeValue = "support";

export const ConversationsCreateRequestTypeValue = {
    Support: "support",
} as const;
