/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CustomSchemaFragmentsSetRequestType = "app_fragment" | "custom_type_fragment" | "tenant_fragment";

export const CustomSchemaFragmentsSetRequestType = {
    AppFragment: "app_fragment",
    CustomTypeFragment: "custom_type_fragment",
    TenantFragment: "tenant_fragment",
} as const;
