/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export interface ErrorNotFound extends DevRevBeta.ErrorBase {
    type: DevRevBeta.ErrorNotFoundType;
}
