/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export interface ErrorBadRequest extends DevRevBeta.ErrorBase {
    type: DevRevBeta.ErrorBadRequestType;
}
