/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ErrorInternalServerErrorType = "internal_error";

export const ErrorInternalServerErrorType = {
    InternalError: "internal_error",
} as const;
