/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ErrorTooManyRequestsType = "too_many_requests";

export const ErrorTooManyRequestsType = {
    TooManyRequests: "too_many_requests",
} as const;
