/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export interface ErrorServiceUnavailable extends DevRevBeta.ErrorBase {
    type: DevRevBeta.ErrorServiceUnavailableType;
}
