/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ErrorServiceUnavailableType = "service_unavailable";

export const ErrorServiceUnavailableType = {
    ServiceUnavailable: "service_unavailable",
} as const;
