/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ErrorBadRequestValueNotPermitted {
    /** The field whose value is not permitted. */
    fieldName: string;
    /** The reason the value isn't permitted. */
    reason?: string;
}
