/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ErrorUnauthorizedType = "unauthenticated";

export const ErrorUnauthorizedType = {
    Unauthenticated: "unauthenticated",
} as const;
