/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export interface IssueSummary extends DevRevBeta.WorkBaseSummary {
    priority?: DevRevBeta.IssuePriority;
}
