/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

/**
 * The response to getting a link's information.
 */
export interface LinksGetResponse {
    link: DevRevBeta.Link;
}
