/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type LinkEndpointType =
    | "capability"
    | "conversation"
    | "enhancement"
    | "feature"
    | "issue"
    | "product"
    | "ticket";

export const LinkEndpointType = {
    Capability: "capability",
    Conversation: "conversation",
    Enhancement: "enhancement",
    Feature: "feature",
    Issue: "issue",
    Product: "product",
    Ticket: "ticket",
} as const;
