/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

/**
 * The response to creating a new link.
 */
export interface LinksCreateResponse {
    link: DevRevBeta.Link;
}
