/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

/**
 * The response to link a rev user to a rev org.
 */
export interface LinkRevUserToRevOrgResponse {
    revUser: DevRevBeta.RevUser;
}
