/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export type LinkEndpointSummary =
    | DevRevBeta.LinkEndpointSummary.Capability
    | DevRevBeta.LinkEndpointSummary.Conversation
    | DevRevBeta.LinkEndpointSummary.Enhancement
    | DevRevBeta.LinkEndpointSummary.Feature
    | DevRevBeta.LinkEndpointSummary.Issue
    | DevRevBeta.LinkEndpointSummary.Product
    | DevRevBeta.LinkEndpointSummary.Ticket;

export declare namespace LinkEndpointSummary {
    interface Capability extends DevRevBeta.PartBaseSummary, _Base {
        type: "capability";
    }

    interface Conversation extends DevRevBeta.ConversationSummary, _Base {
        type: "conversation";
    }

    interface Enhancement extends DevRevBeta.PartBaseSummary, _Base {
        type: "enhancement";
    }

    interface Feature extends DevRevBeta.PartBaseSummary, _Base {
        type: "feature";
    }

    interface Issue extends DevRevBeta.IssueSummary, _Base {
        type: "issue";
    }

    interface Product extends DevRevBeta.PartBaseSummary, _Base {
        type: "product";
    }

    interface Ticket extends DevRevBeta.TicketSummary, _Base {
        type: "ticket";
    }

    interface _Base {
        type: DevRevBeta.LinkEndpointType;
    }
}
