/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export interface OrgBaseSummary extends DevRevBeta.AtomBaseSummary {
    /** Name of the Organization. */
    displayName?: string;
}
