/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export interface OrgBase extends DevRevBeta.AtomBase {
    /** Name of the Organization. */
    displayName?: string;
}
