/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export interface PartBaseSummary extends DevRevBeta.AtomBaseSummary {
    /** Name of the part. */
    name: string;
}
