/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

/**
 * The response to getting a Rev organization's information.
 */
export interface RevOrgsGetResponse {
    revOrg: DevRevBeta.RevOrg;
}
