/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

/**
 * Response object to updating Rev organization's information.
 */
export interface RevOrgsUpdateResponse {
    revOrg: DevRevBeta.RevOrg;
}
