/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RevOrg {
    /** Custom schema fragments. */
    customSchemaFragments?: string[];
    /** Description of the Rev organization. */
    description?: string;
    /** Company's domain name. Example - 'devrev.ai'. */
    domain?: string;
    /**
     * External ref is a unique identifier for the Rev (customer)
     * organization from your primary customer system of records. If none
     * is specified, a system-generated identifier will be assigned to the
     * organization.
     *
     */
    externalRef?: string;
    /** Stock schema fragment. */
    stockSchemaFragment?: string;
}
