/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

/**
 * The returned Rev user.
 */
export interface RevUsersGetResponse {
    revUser: DevRevBeta.RevUser;
}
