/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SchemaEnumFieldDescriptor {
    /** Allowed values for the field. */
    allowedValues?: string[];
    /** Default value. */
    defaultValue?: string;
}
