/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export interface SchemaIdFieldDescriptor extends DevRevBeta.SchemaFieldDescriptorBase {
    /** Default value. */
    defaultValue?: string;
    /** Object ID types. Required when field type is ID. */
    idType?: string[];
}
