/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SchemaIdFieldDescriptor {
    /** Default value. */
    defaultValue?: string;
    /** Object ID types. Required when field type is ID. */
    idType?: string[];
}
