/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export interface SchemaBoolFieldDescriptor extends DevRevBeta.SchemaFieldDescriptorBase {
    /** Default value. */
    defaultValue?: boolean;
}
