/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The schema of ui specific fields.
 */
export interface SchemaFieldUiMetadata {
    /** Display name of the field. */
    displayName?: string;
}
