/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export interface SchemaCompositeListFieldDescriptor extends DevRevBeta.SchemaFieldDescriptorBase {
    /** Composite type. Required when field type is composite. */
    compositeType?: string;
}
