/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SchemaCompositeFieldDescriptor {
    /** Composite type. Required when field type is composite. */
    compositeType?: string;
}
