/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SchemaTokensFieldDescriptor {
    /** The contained substring. */
    contains?: string;
    /** Default value. */
    defaultValue?: string;
    /** The exact string length. */
    eqLen?: number;
    /** The maximum string length. */
    maxLen?: number;
    /** The minimum string length. */
    minLen?: number;
    /** The string pattern (regular expression). */
    pattern?: string;
    /** The string prefix. */
    prefix?: string;
    /** The string suffix. */
    suffix?: string;
}
