/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export interface SchemaEnumFieldDescriptor extends DevRevBeta.SchemaFieldDescriptorBase {
    /** Allowed values for the field. */
    allowedValues: string[];
    /** Default value. */
    defaultValue?: string;
}
