/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export interface SchemaDoubleFieldDescriptor extends DevRevBeta.SchemaFieldDescriptorBase {
    /** Default value. */
    defaultValue?: number;
}
