/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export type SchemaFieldDescriptorArrayType =
    | DevRevBeta.SchemaFieldDescriptorArrayType.Bool
    | DevRevBeta.SchemaFieldDescriptorArrayType.Composite
    | DevRevBeta.SchemaFieldDescriptorArrayType.Double
    | DevRevBeta.SchemaFieldDescriptorArrayType.Enum
    | DevRevBeta.SchemaFieldDescriptorArrayType.Id
    | DevRevBeta.SchemaFieldDescriptorArrayType.Int
    | DevRevBeta.SchemaFieldDescriptorArrayType.RichText
    | DevRevBeta.SchemaFieldDescriptorArrayType.Text
    | DevRevBeta.SchemaFieldDescriptorArrayType.Timestamp
    | DevRevBeta.SchemaFieldDescriptorArrayType.Tokens;

export declare namespace SchemaFieldDescriptorArrayType {
    interface Bool extends DevRevBeta.SchemaBoolListFieldDescriptor, _Base {
        baseType: "bool";
    }

    interface Composite extends DevRevBeta.SchemaCompositeListFieldDescriptor, _Base {
        baseType: "composite";
    }

    interface Double extends DevRevBeta.SchemaDoubleListFieldDescriptor, _Base {
        baseType: "double";
    }

    interface Enum extends DevRevBeta.SchemaEnumListFieldDescriptor, _Base {
        baseType: "enum";
    }

    interface Id extends DevRevBeta.SchemaIdListFieldDescriptor, _Base {
        baseType: "id";
    }

    interface Int extends DevRevBeta.SchemaIntListFieldDescriptor, _Base {
        baseType: "int";
    }

    interface RichText extends DevRevBeta.SchemaRichTextListFieldDescriptor, _Base {
        baseType: "rich_text";
    }

    interface Text extends DevRevBeta.SchemaTextListFieldDescriptor, _Base {
        baseType: "text";
    }

    interface Timestamp extends DevRevBeta.SchemaTimestampListFieldDescriptor, _Base {
        baseType: "timestamp";
    }

    interface Tokens extends DevRevBeta.SchemaTokensListFieldDescriptor, _Base {
        baseType: "tokens";
    }

    interface _Base {
        /** The maximum array length. */
        maxItems?: number;
        /** The minimum array length. */
        minItems?: number;
    }
}
