/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SchemaFieldDescriptorFieldType =
    | "array"
    | "bool"
    | "composite"
    | "double"
    | "enum"
    | "id"
    | "int"
    | "rich_text"
    | "text"
    | "timestamp"
    | "tokens";

export const SchemaFieldDescriptorFieldType = {
    Array: "array",
    Bool: "bool",
    Composite: "composite",
    Double: "double",
    Enum: "enum",
    Id: "id",
    Int: "int",
    RichText: "rich_text",
    Text: "text",
    Timestamp: "timestamp",
    Tokens: "tokens",
} as const;
