/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export interface SchemaFieldDescriptorBase {
    /** Description of the field. */
    description?: string;
    /**
     * Whether this field is filterable, groupable and sortable.
     *
     */
    isFilterable?: boolean;
    /**
     * Whether this field can hold Personally Identifiable Information
     * (PII).
     *
     */
    isPii?: boolean;
    /** Whether this field is required or not. */
    isRequired?: boolean;
    /** Name of the field. */
    name: string;
    /** Type this field is from. */
    origin?: string;
    ui?: DevRevBeta.SchemaFieldUiMetadata;
}
