/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Updates an object's stage.
 */
export interface StageUpdate {
    /**
     * The updated name of the stage, otherwise unchanged if not set.
     *
     */
    name?: string;
}
