/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Describes the current stage of a work item.
 */
export interface Stage {
    /** Current stage name of the work item. */
    name: string;
}
