/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Override for the allowed values of a stock field enum.
 */
export type StockFieldEnumOverride = Record<string, unknown>;
