/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export interface StockSchemaFragmentsListResponse {
    /**
     * The cursor to resume iteration from, otherwise if not provided,
     * then iteration starts from the beginning.
     *
     */
    cursor?: string;
    /** The stock schema fragments. */
    result: DevRevBeta.StockSchemaFragment[];
}
