/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export interface SubtypesListResponse {
    /** List of subtypes. */
    subtypes: DevRevBeta.Subtype[];
}
