/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

/**
 * Updated Sys user object.
 */
export interface SysUsersUpdateResponse {
    sysUser: DevRevBeta.SysUser;
}
