/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export type TimelineEntry = DevRevBeta.TimelineEntry.TimelineComment;

export declare namespace TimelineEntry {
    interface TimelineComment extends DevRevBeta.TimelineComment {
        type: "timeline_comment";
    }
}
