/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TimelineEntryType = "timeline_comment";

export const TimelineEntryType = {
    TimelineComment: "timeline_comment",
} as const;
