/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export interface TimelineComment {
    /** The artifacts for the comment. */
    artifacts?: DevRevBeta.ArtifactSummary[];
    /**
     * The comment's body. If the comment has been deleted, then no body
     * will appear in the response.
     *
     */
    body?: string;
    bodyType?: DevRevBeta.TimelineCommentBodyType;
    /** The SnapKit Body of the comment. */
    snapKitBody?: Record<string, unknown>;
}
