/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

/**
 * The response to unlink a rev user from a rev org.
 */
export interface UnlinkRevUserFromRevOrgResponse {
    revUser: DevRevBeta.RevUser;
}
