/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export interface UserBaseSummary {
    /**
     * The user's display name. The name is non-unique and mutable.
     *
     */
    displayName?: string;
    displayPicture?: DevRevBeta.ArtifactSummary;
    /** Email address of the user. */
    email?: string;
    /** Full name of the user. */
    fullName?: string;
    state?: DevRevBeta.UserState;
}
