/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export type UserSummary =
    | DevRevBeta.UserSummary.DevUser
    | DevRevBeta.UserSummary.RevUser
    | DevRevBeta.UserSummary.SysUser;

export declare namespace UserSummary {
    interface DevUser extends DevRevBeta.UserBaseSummary {
        type: "dev_user";
    }

    interface RevUser extends DevRevBeta.RevUserSummary {
        type: "rev_user";
    }

    interface SysUser extends DevRevBeta.UserBaseSummary {
        type: "sys_user";
    }
}
