/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UserType = "dev_user" | "rev_user" | "sys_user";

export const UserType = {
    DevUser: "dev_user",
    RevUser: "rev_user",
    SysUser: "sys_user",
} as const;
