/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "..";

export interface WorkBaseSummary extends DevRevBeta.AtomBaseSummary {
    /** Title of the work object. */
    title: string;
}
