/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CustomSchemaFragmentsGetRequest {
    /**
     * The ID of the custom schema fragment.
     */
    id: string;
}
