/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CustomStatesListRequest {
    cursor?: string;
    isFinal?: boolean;
    limit?: number;
    name?: string | string[];
    ordinal?: number | number[];
    sortBy?: string | string[];
}
