/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CustomStagesListRequest {
    cursor?: string;
    limit?: number;
    marketplaceRefId?: string;
    name?: string | string[];
    ordinal?: number | number[];
    sortBy?: string | string[];
    stateIdId?: string;
}
