/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "../../../..";

export interface CustomSchemaFragmentsListRequest {
    app?: string | string[];
    cursor?: string;
    leafType?: string | string[];
    limit?: number;
    sortBy?: string | string[];
    subtype?: string | string[];
    types?: DevRevBeta.CustomSchemaFragmentType | DevRevBeta.CustomSchemaFragmentType[];
}
