/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface StockSchemaFragmentsListRequest {
    cursor?: string;
    leafType?: string | string[];
    limit?: number;
    sortBy?: string | string[];
}
