/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SubtypesListRequest {
    /**
     * Leaf type for which subtypes are required.
     */
    leafType: string;
}
