/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const AggregatedSchemaGetResponse: core.serialization.ObjectSchema<
    serializers.AggregatedSchemaGetResponse.Raw,
    DevRevBeta.AggregatedSchemaGetResponse
> = core.serialization.object({
    schema: core.serialization.lazy(async () => (await import("..")).AggregatedSchema),
});

export declare namespace AggregatedSchemaGetResponse {
    interface Raw {
        schema: serializers.AggregatedSchema.Raw;
    }
}
