/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const AggregatedSchema: core.serialization.Schema<
    serializers.AggregatedSchema.Raw,
    DevRevBeta.AggregatedSchema
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace AggregatedSchema {
    type Raw = Record<string, unknown>;
}
