/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const AtomBaseSummary: core.serialization.ObjectSchema<
    serializers.AtomBaseSummary.Raw,
    DevRevBeta.AtomBaseSummary
> = core.serialization.object({
    displayId: core.serialization.property("display_id", core.serialization.string().optional()),
    id: core.serialization.string(),
});

export declare namespace AtomBaseSummary {
    interface Raw {
        display_id?: string | null;
        id: string;
    }
}
