/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const CapabilitySummary: core.serialization.ObjectSchema<
    serializers.CapabilitySummary.Raw,
    DevRevBeta.CapabilitySummary
> = core.serialization.lazyObject(async () => (await import("..")).PartBaseSummary);

export declare namespace CapabilitySummary {
    type Raw = serializers.PartBaseSummary.Raw;
}
