/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const ConversationsListResponse: core.serialization.ObjectSchema<
    serializers.ConversationsListResponse.Raw,
    DevRevBeta.ConversationsListResponse
> = core.serialization.object({
    conversations: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("..")).Conversation)
    ),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
    prevCursor: core.serialization.property("prev_cursor", core.serialization.string().optional()),
});

export declare namespace ConversationsListResponse {
    interface Raw {
        conversations: serializers.Conversation.Raw[];
        next_cursor?: string | null;
        prev_cursor?: string | null;
    }
}
