/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const ConversationsCreateRequestTypeValue: core.serialization.Schema<
    serializers.ConversationsCreateRequestTypeValue.Raw,
    DevRevBeta.ConversationsCreateRequestTypeValue
> = core.serialization.enum_(["support"]);

export declare namespace ConversationsCreateRequestTypeValue {
    type Raw = "support";
}
