/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const ConversationsCreateRequestMessage: core.serialization.ObjectSchema<
    serializers.ConversationsCreateRequestMessage.Raw,
    DevRevBeta.ConversationsCreateRequestMessage
> = core.serialization.object({
    artifacts: core.serialization.list(core.serialization.string()).optional(),
    body: core.serialization.string().optional(),
});

export declare namespace ConversationsCreateRequestMessage {
    interface Raw {
        artifacts?: string[] | null;
        body?: string | null;
    }
}
