/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const CustomSchemaFragmentsSetRequestCustomTypeFragment: core.serialization.ObjectSchema<
    serializers.CustomSchemaFragmentsSetRequestCustomTypeFragment.Raw,
    DevRevBeta.CustomSchemaFragmentsSetRequestCustomTypeFragment
> = core.serialization.object({
    stockFieldEnumOverrides: core.serialization.property(
        "stock_field_enum_overrides",
        core.serialization
            .list(core.serialization.lazy(async () => (await import("..")).StockFieldEnumOverride))
            .optional()
    ),
    subtype: core.serialization.string(),
    subtypeDisplayName: core.serialization.property("subtype_display_name", core.serialization.string().optional()),
});

export declare namespace CustomSchemaFragmentsSetRequestCustomTypeFragment {
    interface Raw {
        stock_field_enum_overrides?: serializers.StockFieldEnumOverride.Raw[] | null;
        subtype: string;
        subtype_display_name?: string | null;
    }
}
