/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const CustomSchemaFragmentsSetRequestAppFragment: core.serialization.ObjectSchema<
    serializers.CustomSchemaFragmentsSetRequestAppFragment.Raw,
    DevRevBeta.CustomSchemaFragmentsSetRequestAppFragment
> = core.serialization.object({
    app: core.serialization.string(),
    appFragmentName: core.serialization.property("app_fragment_name", core.serialization.string()),
});

export declare namespace CustomSchemaFragmentsSetRequestAppFragment {
    interface Raw {
        app: string;
        app_fragment_name: string;
    }
}
