/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const CustomStatesListResponse: core.serialization.ObjectSchema<
    serializers.CustomStatesListResponse.Raw,
    DevRevBeta.CustomStatesListResponse
> = core.serialization.object({
    cursor: core.serialization.string().optional(),
    result: core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).CustomState)),
});

export declare namespace CustomStatesListResponse {
    interface Raw {
        cursor?: string | null;
        result: serializers.CustomState.Raw[];
    }
}
