/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const CustomSchemaFragment: core.serialization.ObjectSchema<
    serializers.CustomSchemaFragment.Raw,
    DevRevBeta.CustomSchemaFragment
> = core.serialization.object({
    type: core.serialization.lazy(async () => (await import("..")).CustomSchemaFragmentType),
});

export declare namespace CustomSchemaFragment {
    interface Raw {
        type: serializers.CustomSchemaFragmentType.Raw;
    }
}
