/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const CustomStage: core.serialization.ObjectSchema<serializers.CustomStage.Raw, DevRevBeta.CustomStage> =
    core.serialization.lazyObject(async () => (await import("..")).AtomBase);

export declare namespace CustomStage {
    type Raw = serializers.AtomBase.Raw;
}
