/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const CustomSchemaFragmentsSetRequestTenantFragment: core.serialization.Schema<
    serializers.CustomSchemaFragmentsSetRequestTenantFragment.Raw,
    DevRevBeta.CustomSchemaFragmentsSetRequestTenantFragment
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace CustomSchemaFragmentsSetRequestTenantFragment {
    type Raw = Record<string, unknown>;
}
