/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const CustomStagesGetResponse: core.serialization.ObjectSchema<
    serializers.CustomStagesGetResponse.Raw,
    DevRevBeta.CustomStagesGetResponse
> = core.serialization.object({
    customStage: core.serialization.property(
        "custom_stage",
        core.serialization.lazyObject(async () => (await import("..")).CustomStage)
    ),
});

export declare namespace CustomStagesGetResponse {
    interface Raw {
        custom_stage: serializers.CustomStage.Raw;
    }
}
