/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const CustomSchemaFragmentsListResponse: core.serialization.ObjectSchema<
    serializers.CustomSchemaFragmentsListResponse.Raw,
    DevRevBeta.CustomSchemaFragmentsListResponse
> = core.serialization.object({
    cursor: core.serialization.string().optional(),
    result: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("..")).CustomSchemaFragment)
    ),
});

export declare namespace CustomSchemaFragmentsListResponse {
    interface Raw {
        cursor?: string | null;
        result: serializers.CustomSchemaFragment.Raw[];
    }
}
