/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const CustomSchemaFragmentsSetRequestType: core.serialization.Schema<
    serializers.CustomSchemaFragmentsSetRequestType.Raw,
    DevRevBeta.CustomSchemaFragmentsSetRequestType
> = core.serialization.enum_(["app_fragment", "custom_type_fragment", "tenant_fragment"]);

export declare namespace CustomSchemaFragmentsSetRequestType {
    type Raw = "app_fragment" | "custom_type_fragment" | "tenant_fragment";
}
