/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const CustomSchemaFragmentsGetResponse: core.serialization.ObjectSchema<
    serializers.CustomSchemaFragmentsGetResponse.Raw,
    DevRevBeta.CustomSchemaFragmentsGetResponse
> = core.serialization.object({
    fragment: core.serialization.lazyObject(async () => (await import("..")).CustomSchemaFragment),
});

export declare namespace CustomSchemaFragmentsGetResponse {
    interface Raw {
        fragment: serializers.CustomSchemaFragment.Raw;
    }
}
