/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const CustomSchemaFragmentsSetRequest: core.serialization.Schema<
    serializers.CustomSchemaFragmentsSetRequest.Raw,
    DevRevBeta.CustomSchemaFragmentsSetRequest
> = core.serialization
    .union("type", {
        app_fragment: core.serialization.lazyObject(
            async () => (await import("..")).CustomSchemaFragmentsSetRequestAppFragment
        ),
        custom_type_fragment: core.serialization.lazyObject(
            async () => (await import("..")).CustomSchemaFragmentsSetRequestCustomTypeFragment
        ),
        tenant_fragment: core.serialization.object({
            value: core.serialization.lazy(
                async () => (await import("..")).CustomSchemaFragmentsSetRequestTenantFragment
            ),
        }),
    })
    .transform<DevRevBeta.CustomSchemaFragmentsSetRequest>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace CustomSchemaFragmentsSetRequest {
    type Raw =
        | CustomSchemaFragmentsSetRequest.AppFragment
        | CustomSchemaFragmentsSetRequest.CustomTypeFragment
        | CustomSchemaFragmentsSetRequest.TenantFragment;

    interface AppFragment extends serializers.CustomSchemaFragmentsSetRequestAppFragment.Raw {
        type: "app_fragment";
    }

    interface CustomTypeFragment extends serializers.CustomSchemaFragmentsSetRequestCustomTypeFragment.Raw {
        type: "custom_type_fragment";
    }

    interface TenantFragment {
        type: "tenant_fragment";
        value: serializers.CustomSchemaFragmentsSetRequestTenantFragment.Raw;
    }
}
