/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const ErrorInternalServerErrorType: core.serialization.Schema<
    serializers.ErrorInternalServerErrorType.Raw,
    DevRevBeta.ErrorInternalServerErrorType
> = core.serialization.enum_(["internal_error"]);

export declare namespace ErrorInternalServerErrorType {
    type Raw = "internal_error";
}
