/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const ErrorInternalServerErrorInternalError: core.serialization.Schema<
    serializers.ErrorInternalServerErrorInternalError.Raw,
    DevRevBeta.ErrorInternalServerErrorInternalError
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace ErrorInternalServerErrorInternalError {
    type Raw = Record<string, unknown>;
}
