/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const ErrorUnauthorizedType: core.serialization.Schema<
    serializers.ErrorUnauthorizedType.Raw,
    DevRevBeta.ErrorUnauthorizedType
> = core.serialization.enum_(["unauthenticated"]);

export declare namespace ErrorUnauthorizedType {
    type Raw = "unauthenticated";
}
