/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const ErrorBadRequestParseError: core.serialization.Schema<
    serializers.ErrorBadRequestParseError.Raw,
    DevRevBeta.ErrorBadRequestParseError
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace ErrorBadRequestParseError {
    type Raw = Record<string, unknown>;
}
