/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const ErrorServiceUnavailableServiceUnavailable: core.serialization.Schema<
    serializers.ErrorServiceUnavailableServiceUnavailable.Raw,
    DevRevBeta.ErrorServiceUnavailableServiceUnavailable
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace ErrorServiceUnavailableServiceUnavailable {
    type Raw = Record<string, unknown>;
}
