/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const ErrorBase: core.serialization.ObjectSchema<serializers.ErrorBase.Raw, DevRevBeta.ErrorBase> =
    core.serialization.object({
        message: core.serialization.string().optional(),
    });

export declare namespace ErrorBase {
    interface Raw {
        message?: string | null;
    }
}
