/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const ErrorBadRequestInvalidEnumValue: core.serialization.ObjectSchema<
    serializers.ErrorBadRequestInvalidEnumValue.Raw,
    DevRevBeta.ErrorBadRequestInvalidEnumValue
> = core.serialization.object({
    allowedValues: core.serialization.property("allowed_values", core.serialization.list(core.serialization.string())),
    fieldName: core.serialization.property("field_name", core.serialization.string()),
    value: core.serialization.string(),
});

export declare namespace ErrorBadRequestInvalidEnumValue {
    interface Raw {
        allowed_values: string[];
        field_name: string;
        value: string;
    }
}
