/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const ErrorForbiddenType: core.serialization.Schema<
    serializers.ErrorForbiddenType.Raw,
    DevRevBeta.ErrorForbiddenType
> = core.serialization.enum_(["forbidden"]);

export declare namespace ErrorForbiddenType {
    type Raw = "forbidden";
}
