/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const ErrorForbidden: core.serialization.ObjectSchema<
    serializers.ErrorForbidden.Raw,
    DevRevBeta.ErrorForbidden
> = core.serialization.object({
    type: core.serialization.lazy(async () => (await import("..")).ErrorForbiddenType).optional(),
});

export declare namespace ErrorForbidden {
    interface Raw {
        type?: serializers.ErrorForbiddenType.Raw | null;
    }
}
