/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const ErrorServiceUnavailable: core.serialization.ObjectSchema<
    serializers.ErrorServiceUnavailable.Raw,
    DevRevBeta.ErrorServiceUnavailable
> = core.serialization.object({
    type: core.serialization.lazy(async () => (await import("..")).ErrorServiceUnavailableType).optional(),
});

export declare namespace ErrorServiceUnavailable {
    interface Raw {
        type?: serializers.ErrorServiceUnavailableType.Raw | null;
    }
}
