/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const ErrorBadRequestValueNotPermitted: core.serialization.ObjectSchema<
    serializers.ErrorBadRequestValueNotPermitted.Raw,
    DevRevBeta.ErrorBadRequestValueNotPermitted
> = core.serialization.object({
    fieldName: core.serialization.property("field_name", core.serialization.string()),
    reason: core.serialization.string().optional(),
});

export declare namespace ErrorBadRequestValueNotPermitted {
    interface Raw {
        field_name: string;
        reason?: string | null;
    }
}
