/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const ErrorNotFound: core.serialization.ObjectSchema<serializers.ErrorNotFound.Raw, DevRevBeta.ErrorNotFound> =
    core.serialization
        .object({
            type: core.serialization.lazy(async () => (await import("..")).ErrorNotFoundType),
        })
        .extend(core.serialization.lazyObject(async () => (await import("..")).ErrorBase));

export declare namespace ErrorNotFound {
    interface Raw extends serializers.ErrorBase.Raw {
        type: serializers.ErrorNotFoundType.Raw;
    }
}
