/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const ErrorBadRequestBadRequest: core.serialization.Schema<
    serializers.ErrorBadRequestBadRequest.Raw,
    DevRevBeta.ErrorBadRequestBadRequest
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace ErrorBadRequestBadRequest {
    type Raw = Record<string, unknown>;
}
