/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const ErrorNotFoundType: core.serialization.Schema<
    serializers.ErrorNotFoundType.Raw,
    DevRevBeta.ErrorNotFoundType
> = core.serialization.enum_(["not_found"]);

export declare namespace ErrorNotFoundType {
    type Raw = "not_found";
}
