/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const ErrorBadRequestType: core.serialization.Schema<
    serializers.ErrorBadRequestType.Raw,
    DevRevBeta.ErrorBadRequestType
> = core.serialization.enum_([
    "bad_request",
    "invalid_enum_value",
    "invalid_field",
    "missing_required_field",
    "parse_error",
    "value_not_permitted",
]);

export declare namespace ErrorBadRequestType {
    type Raw =
        | "bad_request"
        | "invalid_enum_value"
        | "invalid_field"
        | "missing_required_field"
        | "parse_error"
        | "value_not_permitted";
}
