/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const LinkRevUserToRevOrgResponse: core.serialization.ObjectSchema<
    serializers.LinkRevUserToRevOrgResponse.Raw,
    DevRevBeta.LinkRevUserToRevOrgResponse
> = core.serialization.object({
    revUser: core.serialization.property(
        "rev_user",
        core.serialization.lazyObject(async () => (await import("..")).RevUser)
    ),
});

export declare namespace LinkRevUserToRevOrgResponse {
    interface Raw {
        rev_user: serializers.RevUser.Raw;
    }
}
