/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const LinksCreateResponse: core.serialization.ObjectSchema<
    serializers.LinksCreateResponse.Raw,
    DevRevBeta.LinksCreateResponse
> = core.serialization.object({
    link: core.serialization.lazyObject(async () => (await import("..")).Link),
});

export declare namespace LinksCreateResponse {
    interface Raw {
        link: serializers.Link.Raw;
    }
}
