/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const LinksListResponse: core.serialization.ObjectSchema<
    serializers.LinksListResponse.Raw,
    DevRevBeta.LinksListResponse
> = core.serialization.object({
    links: core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).Link)),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
    prevCursor: core.serialization.property("prev_cursor", core.serialization.string().optional()),
});

export declare namespace LinksListResponse {
    interface Raw {
        links: serializers.Link.Raw[];
        next_cursor?: string | null;
        prev_cursor?: string | null;
    }
}
