/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const Link: core.serialization.ObjectSchema<serializers.Link.Raw, DevRevBeta.Link> = core.serialization.object({
    linkType: core.serialization.property(
        "link_type",
        core.serialization.lazy(async () => (await import("..")).LinkType).optional()
    ),
    source: core.serialization.lazy(async () => (await import("..")).LinkEndpointSummary).optional(),
    target: core.serialization.lazy(async () => (await import("..")).LinkEndpointSummary).optional(),
});

export declare namespace Link {
    interface Raw {
        link_type?: serializers.LinkType.Raw | null;
        source?: serializers.LinkEndpointSummary.Raw | null;
        target?: serializers.LinkEndpointSummary.Raw | null;
    }
}
