/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const LinksGetResponse: core.serialization.ObjectSchema<
    serializers.LinksGetResponse.Raw,
    DevRevBeta.LinksGetResponse
> = core.serialization.object({
    link: core.serialization.lazyObject(async () => (await import("..")).Link),
});

export declare namespace LinksGetResponse {
    interface Raw {
        link: serializers.Link.Raw;
    }
}
