/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const LinkType: core.serialization.Schema<serializers.LinkType.Raw, DevRevBeta.LinkType> =
    core.serialization.enum_([
        "developed_with",
        "imports",
        "is_dependent_on",
        "is_duplicate_of",
        "is_parent_of",
        "is_part_of",
        "is_related_to",
        "serves",
    ]);

export declare namespace LinkType {
    type Raw =
        | "developed_with"
        | "imports"
        | "is_dependent_on"
        | "is_duplicate_of"
        | "is_parent_of"
        | "is_part_of"
        | "is_related_to"
        | "serves";
}
