/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const ListMode: core.serialization.Schema<serializers.ListMode.Raw, DevRevBeta.ListMode> =
    core.serialization.enum_(["after", "before"]);

export declare namespace ListMode {
    type Raw = "after" | "before";
}
