/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const OrgEnvironment: core.serialization.Schema<serializers.OrgEnvironment.Raw, DevRevBeta.OrgEnvironment> =
    core.serialization.enum_(["production", "staging", "test"]);

export declare namespace OrgEnvironment {
    type Raw = "production" | "staging" | "test";
}
