/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../core";
import * as serializers from "..";
import * as DevRevBeta from "../../api";

const _Base = core.serialization.object({
    type: core.serialization.lazy(async () => (await import("..")).OrgType),
});
export const OrgSummary: core.serialization.Schema<serializers.OrgSummary.Raw, DevRevBeta.OrgSummary> =
    core.serialization
        .union("type", {
            rev_org: core.serialization.lazyObject(async () => (await import("..")).OrgBaseSummary).extend(_Base),
        })
        .transform<DevRevBeta.OrgSummary>({
            transform: (value) => value,
            untransform: (value) => value,
        });

export declare namespace OrgSummary {
    type Raw = OrgSummary.RevOrg;

    interface RevOrg extends _Base, serializers.OrgBaseSummary.Raw {
        type: "rev_org";
    }

    interface _Base {
        type: serializers.OrgType.Raw;
    }
}
