/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const OrgType: core.serialization.Schema<serializers.OrgType.Raw, DevRevBeta.OrgType> = core.serialization.enum_(
    ["rev_org"]
);

export declare namespace OrgType {
    type Raw = "rev_org";
}
