/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const RevOrgsListResponse: core.serialization.ObjectSchema<
    serializers.RevOrgsListResponse.Raw,
    DevRevBeta.RevOrgsListResponse
> = core.serialization.object({
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
    prevCursor: core.serialization.property("prev_cursor", core.serialization.string().optional()),
    revOrgs: core.serialization.property(
        "rev_orgs",
        core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).RevOrg))
    ),
});

export declare namespace RevOrgsListResponse {
    interface Raw {
        next_cursor?: string | null;
        prev_cursor?: string | null;
        rev_orgs: serializers.RevOrg.Raw[];
    }
}
