/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const RevOrg: core.serialization.ObjectSchema<serializers.RevOrg.Raw, DevRevBeta.RevOrg> =
    core.serialization.object({
        customSchemaFragments: core.serialization.property(
            "custom_schema_fragments",
            core.serialization.list(core.serialization.string()).optional()
        ),
        description: core.serialization.string().optional(),
        domain: core.serialization.string().optional(),
        externalRef: core.serialization.property("external_ref", core.serialization.string().optional()),
        stockSchemaFragment: core.serialization.property(
            "stock_schema_fragment",
            core.serialization.string().optional()
        ),
    });

export declare namespace RevOrg {
    interface Raw {
        custom_schema_fragments?: string[] | null;
        description?: string | null;
        domain?: string | null;
        external_ref?: string | null;
        stock_schema_fragment?: string | null;
    }
}
