/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const RevOrgSummary: core.serialization.ObjectSchema<serializers.RevOrgSummary.Raw, DevRevBeta.RevOrgSummary> =
    core.serialization.lazyObject(async () => (await import("..")).OrgBaseSummary);

export declare namespace RevOrgSummary {
    type Raw = serializers.OrgBaseSummary.Raw;
}
