/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const RevUsersListResponse: core.serialization.ObjectSchema<
    serializers.RevUsersListResponse.Raw,
    DevRevBeta.RevUsersListResponse
> = core.serialization.object({
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
    prevCursor: core.serialization.property("prev_cursor", core.serialization.string().optional()),
    revUsers: core.serialization.property(
        "rev_users",
        core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).RevUser))
    ),
});

export declare namespace RevUsersListResponse {
    interface Raw {
        next_cursor?: string | null;
        prev_cursor?: string | null;
        rev_users: serializers.RevUser.Raw[];
    }
}
