/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const RevUserSummary: core.serialization.ObjectSchema<
    serializers.RevUserSummary.Raw,
    DevRevBeta.RevUserSummary
> = core.serialization.object({
    externalRef: core.serialization.property("external_ref", core.serialization.string().optional()),
    revOrg: core.serialization.property(
        "rev_org",
        core.serialization.lazy(async () => (await import("..")).OrgSummary).optional()
    ),
});

export declare namespace RevUserSummary {
    interface Raw {
        external_ref?: string | null;
        rev_org?: serializers.OrgSummary.Raw | null;
    }
}
