/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const RevUser: core.serialization.ObjectSchema<serializers.RevUser.Raw, DevRevBeta.RevUser> =
    core.serialization.object({
        description: core.serialization.string().optional(),
        externalRef: core.serialization.property("external_ref", core.serialization.string().optional()),
        revOrg: core.serialization.property(
            "rev_org",
            core.serialization.lazy(async () => (await import("..")).OrgSummary).optional()
        ),
    });

export declare namespace RevUser {
    interface Raw {
        description?: string | null;
        external_ref?: string | null;
        rev_org?: serializers.OrgSummary.Raw | null;
    }
}
