/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const SchemaFieldUiMetadata: core.serialization.ObjectSchema<
    serializers.SchemaFieldUiMetadata.Raw,
    DevRevBeta.SchemaFieldUiMetadata
> = core.serialization.object({
    displayName: core.serialization.property("display_name", core.serialization.string().optional()),
});

export declare namespace SchemaFieldUiMetadata {
    interface Raw {
        display_name?: string | null;
    }
}
