/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const SchemaEnumListFieldDescriptor: core.serialization.ObjectSchema<
    serializers.SchemaEnumListFieldDescriptor.Raw,
    DevRevBeta.SchemaEnumListFieldDescriptor
> = core.serialization.object({
    allowedValues: core.serialization.property(
        "allowed_values",
        core.serialization.list(core.serialization.string()).optional()
    ),
    defaultValue: core.serialization.property(
        "default_value",
        core.serialization.list(core.serialization.string()).optional()
    ),
});

export declare namespace SchemaEnumListFieldDescriptor {
    interface Raw {
        allowed_values?: string[] | null;
        default_value?: string[] | null;
    }
}
