/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const SchemaTimestampFieldDescriptor: core.serialization.ObjectSchema<
    serializers.SchemaTimestampFieldDescriptor.Raw,
    DevRevBeta.SchemaTimestampFieldDescriptor
> = core.serialization.object({
    defaultValue: core.serialization.property("default_value", core.serialization.string().optional()),
});

export declare namespace SchemaTimestampFieldDescriptor {
    interface Raw {
        default_value?: string | null;
    }
}
