/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const SchemaIdFieldDescriptor: core.serialization.ObjectSchema<
    serializers.SchemaIdFieldDescriptor.Raw,
    DevRevBeta.SchemaIdFieldDescriptor
> = core.serialization.object({
    defaultValue: core.serialization.property("default_value", core.serialization.string().optional()),
    idType: core.serialization.property("id_type", core.serialization.list(core.serialization.string()).optional()),
});

export declare namespace SchemaIdFieldDescriptor {
    interface Raw {
        default_value?: string | null;
        id_type?: string[] | null;
    }
}
