/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const SchemaBoolFieldDescriptor: core.serialization.ObjectSchema<
    serializers.SchemaBoolFieldDescriptor.Raw,
    DevRevBeta.SchemaBoolFieldDescriptor
> = core.serialization.object({
    defaultValue: core.serialization.property("default_value", core.serialization.boolean().optional()),
});

export declare namespace SchemaBoolFieldDescriptor {
    interface Raw {
        default_value?: boolean | null;
    }
}
