/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const SchemaCompositeListFieldDescriptor: core.serialization.ObjectSchema<
    serializers.SchemaCompositeListFieldDescriptor.Raw,
    DevRevBeta.SchemaCompositeListFieldDescriptor
> = core.serialization.object({
    compositeType: core.serialization.property("composite_type", core.serialization.string().optional()),
});

export declare namespace SchemaCompositeListFieldDescriptor {
    interface Raw {
        composite_type?: string | null;
    }
}
