/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const SchemaFieldDescriptorArrayTypeBaseType: core.serialization.Schema<
    serializers.SchemaFieldDescriptorArrayTypeBaseType.Raw,
    DevRevBeta.SchemaFieldDescriptorArrayTypeBaseType
> = core.serialization.enum_([
    "bool",
    "composite",
    "double",
    "enum",
    "id",
    "int",
    "rich_text",
    "text",
    "timestamp",
    "tokens",
]);

export declare namespace SchemaFieldDescriptorArrayTypeBaseType {
    type Raw = "bool" | "composite" | "double" | "enum" | "id" | "int" | "rich_text" | "text" | "timestamp" | "tokens";
}
