/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const SchemaIntFieldDescriptor: core.serialization.ObjectSchema<
    serializers.SchemaIntFieldDescriptor.Raw,
    DevRevBeta.SchemaIntFieldDescriptor
> = core.serialization
    .object({
        defaultValue: core.serialization.property("default_value", core.serialization.number().optional()),
        gt: core.serialization.number().optional(),
        gte: core.serialization.number().optional(),
        lt: core.serialization.number().optional(),
        lte: core.serialization.number().optional(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("..")).SchemaFieldDescriptorBase));

export declare namespace SchemaIntFieldDescriptor {
    interface Raw extends serializers.SchemaFieldDescriptorBase.Raw {
        default_value?: number | null;
        gt?: number | null;
        gte?: number | null;
        lt?: number | null;
        lte?: number | null;
    }
}
