/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const SchemaIdListFieldDescriptor: core.serialization.ObjectSchema<
    serializers.SchemaIdListFieldDescriptor.Raw,
    DevRevBeta.SchemaIdListFieldDescriptor
> = core.serialization.object({
    defaultValue: core.serialization.property(
        "default_value",
        core.serialization.list(core.serialization.string()).optional()
    ),
    idType: core.serialization.property("id_type", core.serialization.list(core.serialization.string()).optional()),
});

export declare namespace SchemaIdListFieldDescriptor {
    interface Raw {
        default_value?: string[] | null;
        id_type?: string[] | null;
    }
}
