/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const SchemaFieldDescriptorFieldType: core.serialization.Schema<
    serializers.SchemaFieldDescriptorFieldType.Raw,
    DevRevBeta.SchemaFieldDescriptorFieldType
> = core.serialization.enum_([
    "array",
    "bool",
    "composite",
    "double",
    "enum",
    "id",
    "int",
    "rich_text",
    "text",
    "timestamp",
    "tokens",
]);

export declare namespace SchemaFieldDescriptorFieldType {
    type Raw =
        | "array"
        | "bool"
        | "composite"
        | "double"
        | "enum"
        | "id"
        | "int"
        | "rich_text"
        | "text"
        | "timestamp"
        | "tokens";
}
