/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const SchemaEnumFieldDescriptor: core.serialization.ObjectSchema<
    serializers.SchemaEnumFieldDescriptor.Raw,
    DevRevBeta.SchemaEnumFieldDescriptor
> = core.serialization
    .object({
        allowedValues: core.serialization.property(
            "allowed_values",
            core.serialization.list(core.serialization.string())
        ),
        defaultValue: core.serialization.property("default_value", core.serialization.string().optional()),
    })
    .extend(core.serialization.lazyObject(async () => (await import("..")).SchemaFieldDescriptorBase));

export declare namespace SchemaEnumFieldDescriptor {
    interface Raw extends serializers.SchemaFieldDescriptorBase.Raw {
        allowed_values: string[];
        default_value?: string | null;
    }
}
