/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const SchemaFieldDescriptorBase: core.serialization.ObjectSchema<
    serializers.SchemaFieldDescriptorBase.Raw,
    DevRevBeta.SchemaFieldDescriptorBase
> = core.serialization.object({
    description: core.serialization.string().optional(),
    isFilterable: core.serialization.property("is_filterable", core.serialization.boolean().optional()),
    isPii: core.serialization.property("is_pii", core.serialization.boolean().optional()),
    isRequired: core.serialization.property("is_required", core.serialization.boolean().optional()),
    name: core.serialization.string(),
    origin: core.serialization.string().optional(),
    ui: core.serialization.lazyObject(async () => (await import("..")).SchemaFieldUiMetadata).optional(),
});

export declare namespace SchemaFieldDescriptorBase {
    interface Raw {
        description?: string | null;
        is_filterable?: boolean | null;
        is_pii?: boolean | null;
        is_required?: boolean | null;
        name: string;
        origin?: string | null;
        ui?: serializers.SchemaFieldUiMetadata.Raw | null;
    }
}
