/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const StageUpdate: core.serialization.ObjectSchema<serializers.StageUpdate.Raw, DevRevBeta.StageUpdate> =
    core.serialization.object({
        name: core.serialization.string().optional(),
    });

export declare namespace StageUpdate {
    interface Raw {
        name?: string | null;
    }
}
