/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const StageInit: core.serialization.ObjectSchema<serializers.StageInit.Raw, DevRevBeta.StageInit> =
    core.serialization.object({
        name: core.serialization.string().optional(),
    });

export declare namespace StageInit {
    interface Raw {
        name?: string | null;
    }
}
