/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const StockSchemaFragment: core.serialization.ObjectSchema<
    serializers.StockSchemaFragment.Raw,
    DevRevBeta.StockSchemaFragment
> = core.serialization.lazyObject(async () => (await import("..")).AtomBase);

export declare namespace StockSchemaFragment {
    type Raw = serializers.AtomBase.Raw;
}
