/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const StockFieldEnumOverride: core.serialization.Schema<
    serializers.StockFieldEnumOverride.Raw,
    DevRevBeta.StockFieldEnumOverride
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace StockFieldEnumOverride {
    type Raw = Record<string, unknown>;
}
