/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const StockSchemaFragmentsListResponse: core.serialization.ObjectSchema<
    serializers.StockSchemaFragmentsListResponse.Raw,
    DevRevBeta.StockSchemaFragmentsListResponse
> = core.serialization.object({
    cursor: core.serialization.string().optional(),
    result: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("..")).StockSchemaFragment)
    ),
});

export declare namespace StockSchemaFragmentsListResponse {
    interface Raw {
        cursor?: string | null;
        result: serializers.StockSchemaFragment.Raw[];
    }
}
