/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const SysUsersUpdateResponse: core.serialization.ObjectSchema<
    serializers.SysUsersUpdateResponse.Raw,
    DevRevBeta.SysUsersUpdateResponse
> = core.serialization.object({
    sysUser: core.serialization.property(
        "sys_user",
        core.serialization.lazyObject(async () => (await import("..")).SysUser)
    ),
});

export declare namespace SysUsersUpdateResponse {
    interface Raw {
        sys_user: serializers.SysUser.Raw;
    }
}
