/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const SysUser: core.serialization.ObjectSchema<serializers.SysUser.Raw, DevRevBeta.SysUser> =
    core.serialization.lazyObject(async () => (await import("..")).UserBase);

export declare namespace SysUser {
    type Raw = serializers.UserBase.Raw;
}
