/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const SysUserSummary: core.serialization.ObjectSchema<
    serializers.SysUserSummary.Raw,
    DevRevBeta.SysUserSummary
> = core.serialization.lazyObject(async () => (await import("..")).UserBaseSummary);

export declare namespace SysUserSummary {
    type Raw = serializers.UserBaseSummary.Raw;
}
