/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const SysUsersListResponse: core.serialization.ObjectSchema<
    serializers.SysUsersListResponse.Raw,
    DevRevBeta.SysUsersListResponse
> = core.serialization.object({
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
    prevCursor: core.serialization.property("prev_cursor", core.serialization.string().optional()),
    sysUsers: core.serialization.property(
        "sys_users",
        core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).SysUser))
    ),
});

export declare namespace SysUsersListResponse {
    interface Raw {
        next_cursor?: string | null;
        prev_cursor?: string | null;
        sys_users: serializers.SysUser.Raw[];
    }
}
