/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const TicketSeverity: core.serialization.Schema<serializers.TicketSeverity.Raw, DevRevBeta.TicketSeverity> =
    core.serialization.enum_(["blocker", "high", "low", "medium"]);

export declare namespace TicketSeverity {
    type Raw = "blocker" | "high" | "low" | "medium";
}
