/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../core";
import * as serializers from "..";
import * as DevRevBeta from "../../api";

const _Base = core.serialization.object({
    type: core.serialization.lazy(async () => (await import("..")).TimelineEntryType),
});
export const TimelineEntry: core.serialization.Schema<serializers.TimelineEntry.Raw, DevRevBeta.TimelineEntry> =
    core.serialization
        .union("type", {
            timeline_comment: core.serialization
                .lazyObject(async () => (await import("..")).TimelineComment)
                .extend(_Base),
        })
        .transform<DevRevBeta.TimelineEntry>({
            transform: (value) => value,
            untransform: (value) => value,
        });

export declare namespace TimelineEntry {
    type Raw = TimelineEntry.TimelineComment;

    interface TimelineComment extends _Base, serializers.TimelineComment.Raw {
        type: "timeline_comment";
    }

    interface _Base {
        type: serializers.TimelineEntryType.Raw;
    }
}
