/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../core";
import * as serializers from "..";
import * as DevRevBeta from "../../api";

const _Base = core.serialization.object({
    type: core.serialization.lazy(async () => (await import("..")).UserType),
});
export const UserSummary: core.serialization.Schema<serializers.UserSummary.Raw, DevRevBeta.UserSummary> =
    core.serialization
        .union("type", {
            dev_user: core.serialization.lazyObject(async () => (await import("..")).UserBaseSummary).extend(_Base),
            rev_user: core.serialization.lazyObject(async () => (await import("..")).RevUserSummary).extend(_Base),
            sys_user: core.serialization.lazyObject(async () => (await import("..")).UserBaseSummary).extend(_Base),
        })
        .transform<DevRevBeta.UserSummary>({
            transform: (value) => value,
            untransform: (value) => value,
        });

export declare namespace UserSummary {
    type Raw = UserSummary.DevUser | UserSummary.RevUser | UserSummary.SysUser;

    interface DevUser extends _Base, serializers.UserBaseSummary.Raw {
        type: "dev_user";
    }

    interface RevUser extends _Base, serializers.RevUserSummary.Raw {
        type: "rev_user";
    }

    interface SysUser extends _Base, serializers.UserBaseSummary.Raw {
        type: "sys_user";
    }

    interface _Base {
        type: serializers.UserType.Raw;
    }
}
