/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DevRevBeta from "../../api";
import * as core from "../../core";

export const UserType: core.serialization.Schema<serializers.UserType.Raw, DevRevBeta.UserType> =
    core.serialization.enum_(["dev_user", "rev_user", "sys_user"]);

export declare namespace UserType {
    type Raw = "dev_user" | "rev_user" | "sys_user";
}
