/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "../../../..";

export interface ConversationsCreateRequest {
    /** Description for the conversation. */
    description?: string;
    /** The group that the conversation is associated with. */
    group?: string;
    /** The users in the conversation. */
    members?: string[];
    /** Initial messages on the conversation. */
    messages?: DevRevBeta.ConversationsCreateRequestMessage[];
    stage?: DevRevBeta.StageInit;
    /** Tags associated with the conversation. */
    tags?: DevRevBeta.SetTagWithValue[];
    /** The title for the conversation. */
    title?: string;
    type: DevRevBeta.ConversationsCreateRequestTypeValue;
}
