/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ConversationsExportRequest {
    appliesToParts?: string | string[];
    first?: number;
    group?: string | string[];
    members?: string | string[];
    ownedBy?: string | string[];
    revOrg?: string | string[];
    sourceChannels?: string | string[];
    stageName?: string | string[];
    tags?: string | string[];
}
