/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRevBeta from "../../../..";

export interface ConversationsUpdateRequest {
    appliesToParts?: DevRevBeta.ConversationsUpdateRequestAppliesToParts;
    /** The updated description for the conversation. */
    description?: string;
    /** The group that the conversation is associated with. */
    group?: string;
    /** The ID of the conversation to update. */
    id: string;
    stage?: DevRevBeta.StageUpdate;
    /** The updated status of the conversation. */
    status?: string;
    /** The updated title of the conversation. */
    title?: string;
}
