/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as DevRevBeta from "../../../../../api";
import * as core from "../../../../../core";

export const LinkRevUserToRevOrgRequest: core.serialization.Schema<
    serializers.LinkRevUserToRevOrgRequest.Raw,
    DevRevBeta.LinkRevUserToRevOrgRequest
> = core.serialization.object({
    revOrgDon: core.serialization.property("rev_org_don", core.serialization.string()),
    userDon: core.serialization.property("user_don", core.serialization.string()),
});

export declare namespace LinkRevUserToRevOrgRequest {
    interface Raw {
        rev_org_don: string;
        user_don: string;
    }
}
