/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as DevRevBeta from "../../../../../api";
import * as core from "../../../../../core";

export const RevUsersUpdateRequest: core.serialization.Schema<
    serializers.RevUsersUpdateRequest.Raw,
    DevRevBeta.RevUsersUpdateRequest
> = core.serialization.object({
    customFields: core.serialization.property(
        "custom_fields",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional()
    ),
    customSchemaFragments: core.serialization.property(
        "custom_schema_fragments",
        core.serialization
            .lazyObject(async () => (await import("../../../..")).RevUsersUpdateRequestCustomSchemaFragments)
            .optional()
    ),
    description: core.serialization.string().optional(),
    displayName: core.serialization.property("display_name", core.serialization.string().optional()),
    email: core.serialization.string().optional(),
    externalRef: core.serialization.property("external_ref", core.serialization.string().optional()),
    id: core.serialization.string(),
});

export declare namespace RevUsersUpdateRequest {
    interface Raw {
        custom_fields?: Record<string, unknown> | null;
        custom_schema_fragments?: serializers.RevUsersUpdateRequestCustomSchemaFragments.Raw | null;
        description?: string | null;
        display_name?: string | null;
        email?: string | null;
        external_ref?: string | null;
        id: string;
    }
}
