/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as DevRevBeta from "../../../../../api";
import * as core from "../../../../../core";

export const RevUsersCreateRequest: core.serialization.Schema<
    serializers.RevUsersCreateRequest.Raw,
    DevRevBeta.RevUsersCreateRequest
> = core.serialization.object({
    description: core.serialization.string().optional(),
    displayName: core.serialization.property("display_name", core.serialization.string().optional()),
    email: core.serialization.string().optional(),
    externalRef: core.serialization.property("external_ref", core.serialization.string().optional()),
    phoneNumbers: core.serialization.property(
        "phone_numbers",
        core.serialization.list(core.serialization.string()).optional()
    ),
    revOrg: core.serialization.property("rev_org", core.serialization.string()),
});

export declare namespace RevUsersCreateRequest {
    interface Raw {
        description?: string | null;
        display_name?: string | null;
        email?: string | null;
        external_ref?: string | null;
        phone_numbers?: string[] | null;
        rev_org: string;
    }
}
