/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const DevRevBetaEnvironment = {
    Default: "{protocol}://{hostname}",
} as const;

export type DevRevBetaEnvironment = typeof DevRevBetaEnvironment.Default;
