/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as DevRevBeta from "../../../../../api";
import * as core from "../../../../../core";

export const LinksCreateRequest: core.serialization.Schema<
    serializers.LinksCreateRequest.Raw,
    DevRevBeta.LinksCreateRequest
> = core.serialization.object({
    linkType: core.serialization.property(
        "link_type",
        core.serialization.lazy(async () => (await import("../../../..")).LinkType)
    ),
    source: core.serialization.string(),
    target: core.serialization.string(),
});

export declare namespace LinksCreateRequest {
    interface Raw {
        link_type: serializers.LinkType.Raw;
        source: string;
        target: string;
    }
}
