/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as DevRevBeta from "../../../../../api";
import * as core from "../../../../../core";

export const LinksDeleteRequest: core.serialization.Schema<
    serializers.LinksDeleteRequest.Raw,
    DevRevBeta.LinksDeleteRequest
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace LinksDeleteRequest {
    interface Raw {
        id: string;
    }
}
